spring.application.name=music

spring.datasource.url=${DB_URL:db_url}
spring.datasource.username=${DB_USER:db_user}
spring.datasource.password=${DB_PASSWORD:db_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
